export type Role = 'ADMIN' | 'PROJECT_MANAGER' | 'RESOURCE_MANAGER' | 'EMPLOYEE'

export const ROLES: Record<string, Role> = {
  ADMIN: 'ADMIN',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  RESOURCE_MANAGER: 'RESOURCE_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
} as const

export const ALL_ROLES: Role[] = ['ADMIN', 'PROJECT_MANAGER', 'RESOURCE_MANAGER', 'EMPLOYEE']

export const MANAGEMENT_ROLES: Role[] = ['ADMIN', 'PROJECT_MANAGER', 'RESOURCE_MANAGER']
