/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 if the process is running.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 if the database and critical runtime dependencies are ready.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ready */
                            status?: string;
                            /** @example connected */
                            database?: string;
                        };
                    };
                };
                /** @description Service unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in user
         * @description Authenticates user credentials, rotates session ID, and establishes an HTTP-only session cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example admin@staffora.internal
                         */
                        email: string;
                        /** @example SuperSecret123! */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["UserIdentity"];
                        };
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out user
         * @description Destroys current session and clears the session cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current authenticated identity
         * @description Retrieves the currently logged-in user profile, role, and linked employee details.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Authenticated user details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["UserIdentity"];
                        };
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve CSRF token
         * @description Returns the active synchronizer CSRF token stored in the current session.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSRF token value */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                csrfToken?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List departments */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of active departments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DepartmentListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create department (Admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Department created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Department"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List job roles */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of active job roles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobRoleListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create job role (Admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Job role created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["JobRole"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List employee workforce directory */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    departmentId?: string;
                    jobRoleId?: string;
                    status?: "ACTIVE" | "INACTIVE";
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated employees */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create employee profile */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEmployeeInput"];
                };
            };
            responses: {
                /** @description Employee created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Employee"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get employee detail */
        get: {
            parameters: {
                query?: {
                    startDate?: string;
                    endDate?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Employee detail with skills, allocations, and capacity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["EmployeeDetail"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update employee profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateEmployeeInput"];
                };
            };
            responses: {
                /** @description Employee updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Employee"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List skill catalog */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of skills */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SkillListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create skill (Admin/Resource Manager) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Skill created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Skill"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get employee skills */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of employee skills with proficiency */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["EmployeeSkill"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Assign skill to employee */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        skillId: string;
                        proficiencyLevel: number;
                    };
                };
            };
            responses: {
                /** @description Skill assigned */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["EmployeeSkill"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    status?: "DRAFT" | "PLANNED" | "ACTIVE" | "COMPLETED" | "ARCHIVED";
                    projectManagerEmployeeId?: string;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated projects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectInput"];
                };
            };
            responses: {
                /** @description Project created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Project"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project detail with staffing requirements and allocations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ProjectDetail"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update project */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProjectInput"];
                };
            };
            responses: {
                /** @description Project updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Project"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/projects/{id}/staffing-requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List project staffing requirements */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Staffing requirements */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["StaffingRequirement"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create staffing requirement for project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateStaffingRequirementInput"];
                };
            };
            responses: {
                /** @description Staffing requirement created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["StaffingRequirement"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List allocations */
        get: {
            parameters: {
                query?: {
                    employeeId?: string;
                    projectId?: string;
                    startDate?: string;
                    endDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of allocations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AllocationListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create resource allocation
         * @description Validates employee capacity under row lock before saving. Rejects if total concurrent allocation exceeds 100%.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAllocationInput"];
                };
            };
            responses: {
                /** @description Allocation created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Allocation"];
                        };
                    };
                };
                /** @description Capacity conflict or validation conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CapacityConflictResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update allocation */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAllocationInput"];
                };
            };
            responses: {
                /** @description Allocation updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Allocation"];
                        };
                    };
                };
                /** @description Capacity conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CapacityConflictResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/allocations/{id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End active allocation early */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        endDate: string;
                    };
                };
            };
            responses: {
                /** @description Allocation ended */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Allocation"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocations/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel planned allocation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Allocation cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Allocation"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource-finder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search available resources */
        get: {
            parameters: {
                query: {
                    startDate: string;
                    endDate: string;
                    jobRoleId?: string;
                    departmentId?: string;
                    skillId?: string;
                    minProficiency?: number;
                    minRemainingCapacity?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Search results with peak concurrent allocation and remaining capacity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceFinderResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capacity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query organization capacity */
        get: {
            parameters: {
                query: {
                    startDate: string;
                    endDate: string;
                    departmentId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Capacity summaries across employees */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrganizationCapacityResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Role-scoped dashboard summary */
        get: {
            parameters: {
                query?: {
                    startDate?: string;
                    endDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["DashboardData"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Employee self-view
         * @description Returns self profile, skills, current and upcoming allocations, and capacity.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Employee personal summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["EmployeeSelfView"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            message: string;
            code: string;
            errors: {
                [key: string]: string[];
            };
            meta: Record<string, never>;
            requestId: string;
        };
        CapacityConflictResponse: {
            /** @example Allocation exceeds employee capacity. */
            message: string;
            /** @example CAPACITY_CONFLICT */
            code: string;
            errors: Record<string, never>;
            meta: {
                /** @example 80 */
                peakAllocation: number;
                /** @example 30 */
                requestedAllocation: number;
                /** @example 20 */
                remainingCapacity: number;
                /**
                 * Format: date
                 * @example 2026-11-01
                 */
                conflictStartDate: string;
                /**
                 * Format: date
                 * @example 2026-11-15
                 */
                conflictEndDate: string;
            };
            requestId: string;
        };
        UserIdentity: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "ADMIN" | "PROJECT_MANAGER" | "RESOURCE_MANAGER" | "EMPLOYEE";
            isActive: boolean;
            /** Format: uuid */
            employeeId?: string | null;
            employee?: {
                /** Format: uuid */
                id?: string;
                employeeCode?: string;
                fullName?: string;
                workEmail?: string;
                departmentName?: string;
                jobRoleTitle?: string;
            } | null;
        };
        Department: {
            /** Format: uuid */
            id: string;
            name: string;
            isActive: boolean;
        };
        DepartmentListResponse: {
            data?: components["schemas"]["Department"][];
        };
        JobRole: {
            /** Format: uuid */
            id: string;
            name: string;
            isActive: boolean;
        };
        JobRoleListResponse: {
            data?: components["schemas"]["JobRole"][];
        };
        Skill: {
            /** Format: uuid */
            id: string;
            name: string;
            isActive: boolean;
        };
        SkillListResponse: {
            data?: components["schemas"]["Skill"][];
        };
        EmployeeSkill: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            skillId: string;
            skillName: string;
            proficiencyLevel: number;
        };
        CreateEmployeeInput: {
            employeeCode: string;
            fullName: string;
            /** Format: email */
            workEmail: string;
            /** Format: uuid */
            departmentId: string;
            /** Format: uuid */
            jobRoleId: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
        };
        UpdateEmployeeInput: {
            fullName?: string;
            /** Format: uuid */
            departmentId?: string;
            /** Format: uuid */
            jobRoleId?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
        };
        Employee: {
            /** Format: uuid */
            id: string;
            employeeCode: string;
            fullName: string;
            workEmail: string;
            /** Format: uuid */
            departmentId: string;
            departmentName?: string;
            /** Format: uuid */
            jobRoleId: string;
            jobRoleTitle?: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            /** @default 0 */
            currentAllocation: number;
            /** @default 100 */
            currentRemainingCapacity: number;
        };
        EmployeeDetail: components["schemas"]["Employee"] & {
            skills?: components["schemas"]["EmployeeSkill"][];
            allocations?: components["schemas"]["Allocation"][];
            evaluatedPeriod?: {
                /** Format: date */
                startDate?: string;
                /** Format: date */
                endDate?: string;
                peakConcurrentAllocation?: number;
                remainingCapacity?: number;
            };
        };
        EmployeeListResponse: {
            data?: components["schemas"]["Employee"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        CreateProjectInput: {
            projectCode: string;
            name: string;
            /** Format: uuid */
            projectManagerEmployeeId: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /**
             * @default DRAFT
             * @enum {string}
             */
            status: "DRAFT" | "PLANNED" | "ACTIVE" | "COMPLETED" | "ARCHIVED";
        };
        UpdateProjectInput: {
            name?: string;
            /** Format: uuid */
            projectManagerEmployeeId?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @enum {string} */
            status?: "DRAFT" | "PLANNED" | "ACTIVE" | "COMPLETED" | "ARCHIVED";
        };
        Project: {
            /** Format: uuid */
            id: string;
            projectCode: string;
            name: string;
            /** Format: uuid */
            projectManagerEmployeeId: string;
            projectManagerName?: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** @enum {string} */
            status: "DRAFT" | "PLANNED" | "ACTIVE" | "COMPLETED" | "ARCHIVED";
            /** @default 0 */
            staffingRequirementCount: number;
            /** @default 0 */
            allocatedResourceCount: number;
        };
        ProjectDetail: components["schemas"]["Project"] & {
            staffingRequirements?: components["schemas"]["StaffingRequirement"][];
            allocations?: components["schemas"]["Allocation"][];
        };
        ProjectListResponse: {
            data?: components["schemas"]["Project"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        CreateStaffingRequirementInput: {
            /** Format: uuid */
            jobRoleId: string;
            headcount: number;
            allocationPercentage: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            skills?: {
                /** Format: uuid */
                skillId: string;
                minimumProficiencyLevel: number;
            }[];
        };
        StaffingRequirement: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            jobRoleId: string;
            jobRoleTitle: string;
            headcount: number;
            filledHeadcount: number;
            allocationPercentage: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** @enum {string} */
            status: "OPEN" | "FULFILLED";
            skills?: {
                /** Format: uuid */
                skillId?: string;
                skillName?: string;
                minimumProficiencyLevel?: number;
            }[];
        };
        CreateAllocationInput: {
            /** Format: uuid */
            employeeId: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            jobRoleId: string;
            /** Format: uuid */
            staffingRequirementId?: string | null;
            allocationPercentage: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
        };
        UpdateAllocationInput: {
            /** Format: uuid */
            jobRoleId?: string;
            allocationPercentage?: number;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
        };
        Allocation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            employeeId: string;
            employeeName?: string;
            /** Format: uuid */
            projectId: string;
            projectName?: string;
            projectCode?: string;
            /** Format: uuid */
            jobRoleId: string;
            jobRoleTitle?: string;
            /** Format: uuid */
            staffingRequirementId?: string | null;
            allocationPercentage: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** @enum {string} */
            displayStatus: "PLANNED" | "ACTIVE" | "ENDED" | "CANCELLED";
            /** Format: date-time */
            cancelledAt?: string | null;
        };
        AllocationListResponse: {
            data?: components["schemas"]["Allocation"][];
        };
        ResourceFinderItem: {
            /** Format: uuid */
            employeeId: string;
            employeeCode: string;
            fullName: string;
            workEmail: string;
            jobRoleTitle: string;
            departmentName: string;
            peakConcurrentAllocation: number;
            remainingCapacity: number;
            isAssignable: boolean;
            skills?: components["schemas"]["EmployeeSkill"][];
        };
        ResourceFinderResponse: {
            data?: components["schemas"]["ResourceFinderItem"][];
            meta?: {
                /** Format: date */
                startDate?: string;
                /** Format: date */
                endDate?: string;
                totalResults?: number;
            };
        };
        OrganizationCapacityResponse: {
            data?: {
                /** Format: uuid */
                employeeId?: string;
                fullName?: string;
                jobRoleTitle?: string;
                departmentName?: string;
                peakConcurrentAllocation?: number;
                remainingCapacity?: number;
                /** @enum {string} */
                availabilityStatus?: "FULLY_AVAILABLE" | "PARTIALLY_AVAILABLE" | "FULLY_ALLOCATED";
            }[];
        };
        DashboardData: {
            totalActiveResources: number;
            totalActiveProjects: number;
            fullyAvailableResources: number;
            fullyAllocatedResources: number;
            openStaffingRequirements: number;
            capacityDistribution: {
                fullyAvailable?: number;
                partiallyAvailable?: number;
                fullyAllocated?: number;
            };
            accessibleProjects?: components["schemas"]["Project"][];
        };
        EmployeeSelfView: {
            profile: components["schemas"]["Employee"];
            skills: components["schemas"]["EmployeeSkill"][];
            currentAllocations: components["schemas"]["Allocation"][];
            plannedAllocations: components["schemas"]["Allocation"][];
            currentTotalAllocation: number;
            remainingCapacity: number;
        };
        PaginationMeta: {
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
